### ISSUE TITLE
FlutterExifRotation.rotateImage() crashes on Android devices when using mp4 fileformat

### ISSUE THREAD

**Issue by RasmusGodske** [NGhebreial/flutter_exif_rotation#40]
Running `await FlutterExifRotation.rotateImage(path: video.path);` on android using a .mp4 fileformat causes:

  ```bash
W/ExifInterface(23499): Invalid image.
W/ExifInterface(23499): java.io.IOException: Invalid marker: 0
W/ExifInterface(23499): 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1637)
W/ExifInterface(23499): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1345)
W/ExifInterface(23499): 	at android.media.ExifInterface.<init>(ExifInterface.java:1062)
W/ExifInterface(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage(FlutterExifRotationPlugin.java:160)
W/ExifInterface(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.rotateImage(FlutterExifRotationPlugin.java:150)
W/ExifInterface(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.onMethodCall(FlutterExifRotationPlugin.java:113)
W/ExifInterface(23499): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/ExifInterface(23499): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/ExifInterface(23499): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/ExifInterface(23499): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/ExifInterface(23499): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/ExifInterface(23499): 	at android.os.Looper.loop(Looper.java:136)
W/ExifInterface(23499): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
W/ExifInterface(23499): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface(23499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/ExifInterface(23499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/skia    (23499): --- SkImageDecoder::Factory returned null
E/MethodChannel#flutter_exif_rotation(23499): Failed to handle method call
E/MethodChannel#flutter_exif_rotation(23499): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage(FlutterExifRotationPlugin.java:191)
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.rotateImage(FlutterExifRotationPlugin.java:150)
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.onMethodCall(FlutterExifRotationPlugin.java:113)
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_exif_rotation(23499): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter_exif_rotation(23499): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_exif_rotation(23499): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter_exif_rotation(23499): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter_exif_rotation(23499): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
E/MethodChannel#flutter_exif_rotation(23499): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_exif_rotation(23499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#flutter_exif_rotation(23499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  ```

I have tried using both `flutter_exif_rotation: ^0.3.2` and `flutter_exif_rotation: ^0.4.1` both with same result.

**I have tested on:**
- Huawei P20 Pro -  Android version 10 (Does not work)
- ONE A2003 - Android 6.0.1 (Does not work)
- Iphone (Does work)

<details>
  <summary>Flutter Doctor</summary>
  
  
  ```bash
  Doctor summary (to see all details, run flutter doctor -v):
  [√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.867], locale da-DK)
  [√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
  [√] Chrome - develop for the web
  [√] Android Studio (version 3.6)
  [√] IntelliJ IDEA Community Edition (version 2019.2)
  [√] VS Code (version 1.54.3)
  [√] Connected device (3 available)
  • No issues found!
  ```
  
</details>

**Comment by NGhebreial** [comment]
well of course, this is a plugin is for images not videos sorry

**Comment by RasmusGodske** [comment]
That is fair enough, funny why it works on IOS though.
