### ISSUE TITLE
Android targetSdkVersion 30 Permission Denied

### ISSUE THREAD

**Issue by JosephNK** [NGhebreial/flutter_exif_rotation#44]
There is an issue where an Android targetSdkVersion 30 permission error occurs.

java.io.FileNotFoundException: /storage/emulated/0/Pictures/1620556973373.jpg: open failed: EACCES (Permission denied)

Log
```
W/System.err( 8462): java.io.FileNotFoundException: /storage/emulated/0/Pictures/1620556973373.jpg: open failed: EACCES (Permission denied)
W/System.err( 8462): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err( 8462): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W/System.err( 8462): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err( 8462): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage(FlutterExifRotationPlugin.java:189)
```

FlutterExifRotationPlugin.java
```
FileOutputStream fOut = new FileOutputStream(file); 
```

**Comment by diver2** [comment]
Have the same. 
After a while I found out that the way the app is written you need "MANAGE_EXTERNAL_STORAGE" permission, but this is a cannon ball shot, won't work in prod (users will just churn)

**Comment by diver2** [comment]
I found a solution, and this implies the prob. is not with this package 
The app is accessing/trying to write to a file that we don't have access.
So, I get the file, copy it to a Temp Dir where we have access and then run flutter exif

```dart
final _dir = await path_provider.getTemporaryDirectory();
String _filename = "YOUR_FILENAME";
const String _extension = 'jpg';  // this is my case
io.File imageCopied = io.File("${_dir.absolute.path}/$_filename.$_extension");
imageCopied.writeAsBytesSync(YOUR_ORIGINAL_IMAGE in List<int> format);
io.File imageEXIF = await FlutterExifRotation.rotateAndSaveImage(path: imageCopied.path);
```

Libraries are
```dart
import 'package:path_provider/path_provider.dart' as path_provider;
import 'dart:io' as io;
import 'package:flutter_exif_rotation/flutter_exif_rotation.dart';
```
