### ISSUE TITLE
RuntimeException: Methods marked with @UiThread must be executed on the main thread

### ISSUE THREAD

**Issue by stefanmusat** [NGhebreial/flutter_exif_rotation#51]
Hi,
I've just implemented this plugin and this is what it throws when calling: 

`await FlutterExifRotation.rotateImage(path: image!.path);`

```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-15-thread-1
E/AndroidRuntime(16887): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1280)
E/AndroidRuntime(16887): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:952)
E/AndroidRuntime(16887): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:169)
E/AndroidRuntime(16887): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(16887): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage(FlutterExifRotationPlugin.kt:83)
E/AndroidRuntime(16887): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.access$launchRotateImage(FlutterExifRotationPlugin.kt:22)
E/AndroidRuntime(16887): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin$onMethodCall$$inlined$runOnBackground$1.run(FlutterExifRotationPlugin.kt:116)
E/AndroidRuntime(16887): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(16887): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(16887): 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by benincasantonio** [comment]
Hi, 
Same problem here!
